# Generated by Django 2.0.4 on 2018-04-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(blank=True, max_length=35)),
                ('nachname', models.CharField(blank=True, max_length=35)),
                ('anmerkung', models.TextField(blank=True)),
            ],
        ),
    ]
